### ISSUE TITLE
011-mobilityDB docker build fail

### ISSUE THREAD

**Issue by abroniewski** [sabman/aicasts.com#99]
When tying to build the docker image, the system fails with error:
  0.202 Cloning into 'MobilityDB'...
  108.4 fatal: not a git repository (or any of the parent directories): .git

I tried to play with the dockerfile.src, updated the git repository address, but it continued to fail. From my fiddling with it today, it may have something to do with SSH keys, but I'm not sure.

**Comment by sabman** [comment]
@abroniewski sorry I'm not actively maintaining this. Have you tried the official docker images? https://github.com/MobilityDB/MobilityDB-docker
